[build]
  command = "npm run copy-demo-assets"
  functions = "netlify/functions"
  publish = "demo"

[[redirects]]
  from = "https://ie-page-transitions.netlify.app/*"
  to = "https://page-transitions.style/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Access-Control-Allow-Origin = "*"